export const defaultLine = {
  countryTop: [],
  factoryDate_Month: [],
  cloudCamRegion: [],
  eu_newCam30Iot: [],
  cn_newCam30Iot: [],
  factoryEquipmentNum: [],
  activeCam: 0,
  newCamRegion: [],
  activeCountry: 0,
  factoryData: [],
  factoryDate: [],
  us_newCam30Iot: [],
  event: 0,
  allActiveCam: 0,
  sg_newCam30Iot: [],
  factoryEquipmentNum_Month: [],
  factoryEquipmentNum_Week: [],
  activeCamRegion: [],
  activeCity: 0,
  aliveVideo: [],
  newCam: 0,
  allActiveCamRegion: [],
  factoryEquipmentNumRank: [[]],
  cloudCam: 0,
  cloudSave: 0,
  cloudSaveToday: '',
  factoryDate_Week: [],
  newCam30Iot: [],
  factoryEquipmentNumRank_week: [[]],
  factoryEquipmentNumRank_month: [[]],
}

export const defaultYiLine = {
  sg_newCam30: [],
  cloudCamRegion: [],
  eu_newCam30: [],
  cn_newCam30: [],
  activeCam: 0,
  newCamRegion: [],
  event: 0,
  newCam30Kami: [],
  countryTop: [],
  us_newCam30: [],
  activeCountry: 0,
  allActiveCam: 0,
  us_newCam30Kami: [],
  activeCamRegion: [],
  activeCity: 0,
  eu_newCam30Kami: [],
  aliveVideo: [],
  newCam: 0,
  sg_newCam30Kami: [],
  cloudCam: 0,
  cloudSave: 0,
  cloudSaveToday: '',
  cn_newCam30Kami: [],
  newCam30: [],
}

export const getLineOption = (legend: string[], axis: any[], series: any[]) => {
  return {
    title: {
      text: '',
    },
    tooltip: {
      trigger: 'axis',
    },
    grid: {
      left: '3%',
      right: '4%',
      bottom: '5%',
      containLabel: true,
    },
    legend: {
      data: legend,
      bottom: 0,
      textStyle: {
        color: 'white',
      },
    },
    toolbox: false,
    xAxis: {
      type: 'category',
      boundarygap: false,
      data: axis,
    },
    yAxis: { type: 'value' },
    series,
  }
}
